# Generated by Django 3.0.6 on 2020-06-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_id',
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
