# Generated by Django 3.0.6 on 2020-06-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0002_auto_20200626_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_num', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='route',
            old_name='name',
            new_name='route_name',
        ),
    ]
