# Generated by Django 3.0.6 on 2020-06-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0003_auto_20200626_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='id',
        ),
        migrations.AlterField(
            model_name='busstop',
            name='stop_num',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
