# Generated by Django 3.0.6 on 2020-06-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0004_auto_20200626_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteAndStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_num', models.IntegerField()),
                ('route_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_app.Route')),
                ('stop_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_app.BusStop')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='bus_stops',
            field=models.ManyToManyField(through='bus_app.RouteAndStop', to='bus_app.BusStop'),
        ),
    ]
