# Generated by Django 3.0.3 on 2020-07-25 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus_app', '0006_additionaluserinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='leapcard_password',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.CreateModel(
            name='FavouriteJourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=10)),
                ('origin_stop', models.CharField(max_length=200)),
                ('destination_stop', models.CharField(max_length=200)),
                ('stops_count', models.PositiveSmallIntegerField()),
                ('save_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('save_date',),
            },
        ),
    ]
